meta_product_name: "Minder"
meta_title: "Minder - Never miss another movie, book, album or concert"
meta_description: ""
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
