meta_product_name: "Minder"
meta_title: "Minder - Never miss another movie, book, album or concert"
meta_description: "Minder will notify you of any upcoming movies, books/
, albums or concerts from your favourite creators. Save content for later/
 and get notified when there is a new release!"
meta_image: "cover.jpg"
twitter_account: "@minder931"
